# Generated by Django 5.1.2 on 2024-11-06 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='zipcode',
            new_name='pincode',
        ),
    ]
